# Generated by Django 3.2.7 on 2021-11-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagenda',
            name='published',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postagenda',
            name='updated',
            field=models.TimeField(auto_now=True),
        ),
    ]
