# Generated by Django 3.2.7 on 2021-11-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_postagenda_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagenda',
            name='file',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
