# Generated by Django 3.2.7 on 2021-11-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='file',
        ),
    ]
