# Generated by Django 3.2.7 on 2021-11-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_remove_agenda_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='published',
            new_name='published1',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='kegiatan',
            new_name='r_kegiatan',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='tanggal',
            new_name='r_tanggal',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='tempat',
            new_name='r_tempat',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='waktu',
            new_name='r_waktu',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='updated',
            new_name='updated1',
        ),
    ]
