# Generated by Django 3.2.7 on 2021-11-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_postagenda_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagenda',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
