# Generated by Django 3.2.7 on 2021-11-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_postagenda_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagenda',
            name='file',
            field=models.FileField(null=True, upload_to='file/'),
        ),
    ]
