# Generated by Django 3.2.7 on 2021-11-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_alter_postagenda_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='nomor',
            field=models.IntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
