# Generated by Django 3.2.7 on 2021-11-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_agenda_nomor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='nomor',
            field=models.IntegerField(),
        ),
    ]
