# Generated by Django 3.2.7 on 2021-11-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_alter_agenda_nomor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='nomor',
        ),
        migrations.AlterField(
            model_name='postagenda',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
