# Generated by Django 3.2.7 on 2021-11-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_auto_20211115_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagenda',
            name='file',
            field=models.FileField(blank='True', null=True, upload_to=''),
        ),
    ]
